### ISSUE TITLE
Question about call convention for dll's called with rundll32

### ISSUE THREAD

**Issue by greatwolf** [ReneNyffenegger/Windows-development#1]
According to your article here: https://renenyffenegger.ch/notes/Windows/dirs/Windows/System32/rundll32_exe/example-dll

rundll32 expects exported dll functions to use `__stdcall` but your use-declspec.c uses `__cdecl` : https://github.com/ReneNyffenegger/Windows-development/blob/master/rundll32.exe/use-declspec.c

Is this really okay? Wouldn't it potentially corrupt the stack if the caller and callee can't agree who's suppose to cleanup afterwards?

BTW, according to this SO answer https://stackoverflow.com/a/38986898/234175, rundll32 expects dll function to follow `__stdcall`.

**Comment by ReneNyffenegger** [comment]
You're right, using `__cdecl` is wrong. I have changed the example to use CALLBACK (which resolves to `__stdcall` when compiling for x86 and to *nothing* when compiling for x64).
